services:
  pdftk-web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - WATCH_DIRECTORY=/app/uploads
    volumes:
      - ./host_uploads:/app/uploads
    container_name: pdftk-web

